### ISSUE TITLE
[Błąd] Aplikacja jest nieresponsywna

### ISSUE THREAD

**Issue by mikolajkalwa** [Gameplayer8850/AOI#1]
Wszystkie operacje związane z pobieraniem danych z zewnętrznych serwerów odbywają się na wątku UI. Aplikacja jest nieresponsywna podczas uruchamiania, oraz podczas wczytywania listy anime.

**Comment by Gameplayer8850** [comment]
W najbliższej przyszłości nie planuję przekształcać danej aplikacji, aby posiadała implementację wielowątkowości. :(
